### ISSUE TITLE
Error al usar glosario en abstract

### ISSUE THREAD

**Issue by rola93** [LaTeXUy/UdelaRTeX#13]
Hola

Estoy usando el template en OverLeaf. Estoy teniendo problemas cuando uso glosarios dentro del abstract (`resumen/abstract.tex`):

```latex
\begin{foreignabstract}

This is my abstract, but when I use \gls{THIS} it throws an error.

\end{foreignabstract}
```

Notar que a lo largo del trabajo uso `\gls` sin problemas, excepto en los captions, ahi si o si tuve que removerlos. En ese caso no me estresa tanto porque es "adentro" del trabajo, sin embargo el abstract es de lo primero que aparece, y por tanto, debería aparecer la sigla con su significado.

Volviendo al punto, me da un error de No PDF:

```
No PDF
This compile didn’t produce a PDF. This can happen if:
There is an unrecoverable LaTeX error. If there are LaTeX errors shown below or in the raw logs, please try to fix them and compile again.
The document environment contains no content. If it’s empty, please add some content and compile again.
This project contains a file called output.pdf. If that file exists, please rename it and compile again.
```
Luego este otro:
```
Incomplete \iffalse; all text was ignored after line 20.                          ‪./tesis.tex, 95‬

<inserted text> 
\fi 
l.95  \include{resumen/abstract}
                              
The file ended while I was skipping conditional text.
This kind of error happens when you say `\if...' and forget
the matching `\fi'. I've inserted a `\fi'; this might work.
```

Y un montón  más, pero cero pista de qué es exactamente lo que esta fallando. 

Alguna idea?

**Comment by jorgepz** [comment]
sugiero que intentes crearte usuario en git.interior y crear un issue en https://git.interior.edu.uy/posgrados/UdelaRTeX o la seguimos por acá

**Comment by jorgepz** [comment]
@mihdicaballero : este error también lo vimos ayer juntos con @rola93  y efectivamente, hay un error al usar el comando \gls en el abstract o en los captions de las figuras. supongo que debe ser un comportamiento esperado del paquete ya que uno supondría que lo más relevante es donde se usan por primera vez las siglas en el cuerpo de la tesis... doy este issue por cerrado y cualquier cosa se reabre. gracias de nuevo @rola93 por detectarlo!
