### ISSUE TITLE
Problema con version en ingles

### ISSUE THREAD

**Issue by rola93** [LaTeXUy/UdelaRTeX#14]
en la segunda y tercera pagina, se genera el siguiente texto:

> Master’s Thesis submitted to the Postgraduate
Program **en** Computer Science, Facultad de
Ingeniería of the Universidad de la República, as
part of the necessary requirements for obtaining the
title of Master in Computer Science

Notar que dice "Program **en** Computer Science", lo cual es inconsistente, debería decir "**in**". Sin embargo, la segunda ocurrencia esta correcta.

Estuve mirando, y seguro el error esta en `udelar.cls` pero no me doy cuenta exactamente dónde. 

El problema al parecer esta en la [linea 708](https://github.com/LaTeXUy/UdelaRTeX/blob/73ed0e5a4d52903716173d9195e30df168246c85/TESIS/udelar.cls#L708):

```latex
%==== Parte de la página II y III ====

\ifbool{eng}{
		\newcommand\frontcover@maintext{\sloppy\nohyphens{\foreign@degreename's\ \foreign@doctype\ submitted to the Postgraduate Program \@tipoescritura~\local@graduatename, \local@maininstitute\ of the Universidad de la Rep{\'u}blica, as part of the necessary requirements for obtaining the title of
		\foreign@degname\ in \local@graduatename.}}	
}{
		\newcommand\frontcover@maintext{ \sloppy\nohyphens{\local@doctype\ de \local@degreename\
		presentada al Programa de Posgrado \@tipoescritura~\local@graduatename, \local@maininstitute\ de la Universidad de la Rep{\'u}blica, como parte de los requisitos
		necesarios para la obtenci{\'o}n del t{\'i}tulo de
		\local@degname\ en \local@graduatename.}}
}
```
 Y la solucion, tiene pinta que va en la [linea 297](https://github.com/LaTeXUy/UdelaRTeX/blob/73ed0e5a4d52903716173d9195e30df168246c85/TESIS/udelar.cls#L297), que es donde se define el comando:
```latex
%==== Pongo si quiero que sea un posgrado "en" algo o "de" algo ====
\newcommand\escritura[1]{% Comando para el tipo de posgrado
	\global\def\@tipoescritura{#1}
}
```

No pude arreglarlo porque se poco de latex, y, no entiendo la sintaxis de la definición del comando (entre varias otras cosas); Capaz alguien pueda ayudarme, agradezco de antemano.

**Comment by jorgepz** [comment]
Hola, excelente. bien encontrado el error! efecitvamente es algo que es fácilmente editable... pero para eso creo que primero hay que resolver este problema https://github.com/LaTeXUy/UdelaRTeX/issues/15 de repos duplicados... en estos días espero que lo podamos conversar con @mihdicaballero y definir eso

**Comment by rolaguna** [comment]
Hola Jorge, gracias por la respuesta.

Podes ayudarme a solucionarlo para arreglarlo en mi fork local? Supera ampliamente mis conocimientos de latex 😅

**Comment by rola93** [comment]
Hola Jorge, gracias por la respuesta.

Podes ayudarme a solucionarlo para arreglarlo en mi fork local? Supera ampliamente mis conocimientos de latex 😅
________________________________
De: Jorge Pérez Zerpa ***@***.***>
Enviado: jueves, 8 de junio de 2023 7:00
Para: LaTeXUy/UdelaRTeX ***@***.***>
Cc: Rodrigo Laguna ***@***.***>; Author ***@***.***>
Asunto: Re: [LaTeXUy/UdelaRTeX] Problema con version en ingles (Issue #14)


Hola, excelente. bien encontrado el error! efecitvamente es algo que es fácilmente editable... pero para eso creo que primero hay que resolver este problema #15<https://github.com/LaTeXUy/UdelaRTeX/issues/15> de repos duplicados... en estos días espero que lo podamos conversar con @mihdicaballero<https://github.com/mihdicaballero> y definir eso

**Comment by mihdicaballero** [comment]
Buenas! Así como dice @jorgepz tenemos que ver como hacemos, para no tener repos duplicados y pasar a tener versiones distintas de la clase. El repo oficial es el que está en el git del Interior: https://git.interior.edu.uy/posgrados/UdelaRTeX

Y ahí también se pueden hacer issues.

**Comment by rola93** [comment]
Entiendo el punto, pero creo que me exprese mal. Por "mi fork local" me refiero a la versión que clone en su momento y lleve a overleaf para trabajar. Estoy a punto de terminar la tesis que estoy escribiendo en ingles basado en esta version. Me queda corregir detalles como este y me gustaría encontrar una solución, pero como dije antes, mis conocimientos de latex son escasos y es por ello que apelo a uds.

________________________________
De: Mihdí Caballero ***@***.***>
Enviado: jueves, 8 de junio de 2023 12:39
Para: LaTeXUy/UdelaRTeX ***@***.***>
Cc: Rodrigo Laguna ***@***.***>; Author ***@***.***>
Asunto: Re: [LaTeXUy/UdelaRTeX] Problema con version en ingles (Issue #14)


Buenas! Así como dice @jorgepz<https://github.com/jorgepz> tenemos que ver como hacemos, para no tener repos duplicados y pasar a tener versiones distintas de la clase. El repo oficial es el que está en el git del Interior: https://git.interior.edu.uy/posgrados/UdelaRTeX

Y ahí también se pueden hacer issues.

**Comment by rola93** [comment]
Por otro lado, respecto a la discusión de donde hostearlo, en git.interior solo pueden colaborar los que tengan usuario ahi, git tiene la ventaja de que cualquiera puede hacerlo. Por ejemplo, este mismo issue no lo puedo levantar ahi y menos que menos abrir un PR.

Intente loguearme con mi usario del gitlab fing y no me dejo 😕


________________________________
De: Mihdí Caballero ***@***.***>
Enviado: jueves, 8 de junio de 2023 12:39
Para: LaTeXUy/UdelaRTeX ***@***.***>
Cc: Rodrigo Laguna ***@***.***>; Author ***@***.***>
Asunto: Re: [LaTeXUy/UdelaRTeX] Problema con version en ingles (Issue #14)


Buenas! Así como dice @jorgepz<https://github.com/jorgepz> tenemos que ver como hacemos, para no tener repos duplicados y pasar a tener versiones distintas de la clase. El repo oficial es el que está en el git del Interior: https://git.interior.edu.uy/posgrados/UdelaRTeX

Y ahí también se pueden hacer issues.

**Comment by jorgepz** [comment]
Ese es uno de los temas a definir.... @mihdicaballero va a consultar a la gente que administra git.interior para ver que tan fácil es crear users para contribuir. Esperemos unos días. Sobre la corrección para tu tesis, parece q lo mas razonable es que lo corrijas en tu versión local... Una opción es modificar a mano la linea 473..poner in directamente...

**Comment by jorgepz** [comment]
pudiste resolver esto @rola93 ? me llegaron las instrucciones para crearse user en git.interior y poder contribuir. podrías registrarte en https://login.interior.edu.uy/, luego iniciar sesión con esa identidad en la pestaña LDAP en https://git.interior.edu.uy/

yo trasladé este issue para gitlab para seguirla ahi https://git.interior.edu.uy/posgrados/UdelaRTeX/-/issues/2

**Comment by jorgepz** [comment]
@rola93 me di cuenta que en realidad solo tendrías que modificar la línea [\escritura[1]{ y \escritura[1]{](https://git.interior.edu.uy/posgrados/UdelaRTeX/-/blob/master/TESIS/tesis.tex#L39) en tu archivo tesis.tex y poner ahi "in"

por otra parte hay otros problemas de idioma que expliqué en el issue de git.interior. cierro este issue y la seguimos en el otro

**Comment by rola93** [comment]
Buenas! No aun no pude resolver. Intente modificar aunque sea solo el mio y no pude ni asi... Ahora mismo no puedo vicharlo, pero voy a intentar con eso ultimo que pusiste a ver si le encuentro la vuelta, cualquier cosa voy al otro issue, gracias!

**Comment by rola93** [comment]
Buenas! volvi sore esto... Yo ya tenia "in" en esa linea, de hecho, todo el resto del documento me lo renderiza en ingles sin problemas (content/chapter/abstract etc), es sólo en esa parte del documento que quedo mal, por eso es un bug... pero no encuentro como arreglarlo, ni de forma generica ni en mi caso particular

**Comment by jorgepz** [comment]
Podemos hacer algún meet en la segunda semana de agosto (luego del inicio de clases)

**Comment by rola93** [comment]
Dale, te escribo por mail para agendar

**Comment by rola93** [comment]
Cierro issue; Me junte con @jorgepz y efectivamente la solucion era lo que el sugería: en [linea 39 de TESIS/tesis.tex](https://git.interior.edu.uy/posgrados/UdelaRTeX/-/blob/master/TESIS/tesis.tex#L39) hay que poner "in":


```latex
\escritura{in} % Se indica que el programa de Posgrado sea "en" o "de" tal área. "in" en inglés.
```
Basicamente, el comando `\escritura{PEPE}` se renderiza como:

```
 as part of the
necessary requirements for obtaining the title of
Master PEPE Computer Science
```

asi que en mi caso, alcanzaba con poner el `in`.

Cierro issue, gracias por el apoyo!
