### ISSUE TITLE
Resolver tema de repos duplicados

### ISSUE THREAD

**Issue by jorgepz** [LaTeXUy/UdelaRTeX#15]
tal como comentaba acá https://groups.io/g/uylatex/message/231 hay repositorios duplicados y este es uno. sugiero [convertir este repo a mirror](https://docs.github.com/en/repositories/creating-and-managing-repositories/duplicating-a-repository) y que [este](https://git.interior.edu.uy/posgrados/UdelaRTeX) quede como oficial

**Comment by mihdicaballero** [comment]
Es una buena sugerencia! A ver cómo se hace para ejecutarlo estos días.

**Comment by jorgepz** [comment]
si @mihdicaballero me da permiso de mantainer en el repo de git.interior podría hacer lo que se indica acá https://open.win.ox.ac.uk/pages/open-science/community/Open-WIN-Community/docs/gitlab/6-1-mirroring-to-github/ y dejar este repo como mirror apuntando al de git.interior

**Comment by jorgepz** [comment]
Decido no hacerlo por ahora ya que se precisa generar una clave pública y privada. Por ahora, dado que es factible crear usuarios en git.interior vacío este repo y solo dejo el readme para poner enlaces y potencial data de interés.

**Comment by mihdicaballero** [comment]
Genial! La seguimos por Gitlab por ahora entonces.
