### ISSUE TITLE
setear CI

### ISSUE THREAD

**Issue by jorgepz** [LaTeXUy/UdelaRTeX#3]

**Comment by mihdicaballero** [comment]
¿Esto sabés hacerlo? Para dejar andando el PDFLaTeX con Biber.

**Comment by jorgepz** [comment]
lo se hacer en gitlab, en github es un poco distinto... sería con github actions por ejemplo esta ... https://github.com/xu-cheng/latex-action  tal vez siguiendo esto https://dev.to/mrturkmen/latex-with-github-actions-4580
en la tarde trato de mirarlo.

de todas formas... habría que discutir si usar biber o no...

**Comment by jorgepz** [comment]
cierro esto porque ahora habría que hacer el seteo en el repo de git.interior ya que mudamos los archivos de acá.
