### ISSUE TITLE
quitar / actualizar guía de estilo

### ISSUE THREAD

**Issue by jorgepz** [LaTeXUy/UdelaRTeX#4]
@MBerguer  tenés alguna sugerencia de enlace para poner en el readme? 

yo por lo pronto sugiero quitar este archivo de este repo _Guía para presentación de una tesis de posgrado_ago 2016.pdf

**Comment by MBerguer** [comment]
Buenas!

Yo ya no estoy como colaborador en la cap, por lo que no te puedo ayudar a decidir en ese aspecto.
Mi recomendación personal es que estaría bueno actualizarlo, juzgando por el nombre del archivo, está desde 2016.

Saludos!

**Comment by jorgepz** [comment]
ok, gracias por la respuesta. Entonces efectivamente lo borro ( en el PR #10  ) y agrego el enlace a la versión que está en el repo de gitposgrados hasta que la gente que define el estilo haga otro documento.
de todas formas, esta clase ahora pasó a ser un documento no oficial, por lo que el estilo es una referencia... según tenemos entendido no hay un estilo oficial aprobado por la udelar a la fecha.
