### ISSUE TITLE
unificar commits de usuarios de Mihdí

### ISSUE THREAD

**Issue by jorgepz** [LaTeXUy/UdelaRTeX#6]
sería bueno unificar la historia del usuario Mihdí Caballero y de @mihdicaballero

**Comment by jorgepz** [comment]
@MBerguer  tendrás alguna idea de como hacer esto? estaría bueno que las contribuciones  https://github.com/LaTeXUy/UdelaRTeX/graphs/contributors queden reflejadas... nosotros hicimos la importación desde github con la url de git.posgrados pero tal vez haya otra forma mejor...
desde ya gracias!

**Comment by MBerguer** [comment]
Buenas!

La verdad no lo hice nunca, pero buscando encontré esto: https://stackoverflow.com/questions/3042437/how-to-change-the-commit-author-for-one-specific-commit

si les funca de más, sino es un tema de github y su configuración local en la máquina, tendría que actualizarlo ahí. este repo venía de gitlab no?

**Comment by jorgepz** [comment]
buenazo! gracias por hacer la búsqueda. lo dejamos abierto por acá para intentarlo a futuro

**Comment by jorgepz** [comment]
lo estuve leyendo... definitivamente no es nada trivial y tampoco creo que sea algo prioritario. cierro y cualquier cosa @mihdicaballero  abrimos de nuevo.
